name: Trigger auto deployment for teste

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/teste-AutoDeployTrigger-a2521715-bbfe-4a42-b8a5-6d3f27ab7c1a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TESTE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.TESTE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTE_REGISTRY_PASSWORD }}
          containerAppName: teste
          resourceGroup: rg-app
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


